### ISSUE TITLE
Add Responsiveness

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/Sukoon#20]
Need to add responsiveness to the pages. Currently, it is only Desktop friendly.

**Comment by pallavi-1812** [comment]
Hello! Can I work on this issue?

**Comment by niloysikdar** [comment]
Hey @pallavi-1812 , glad to see you. You can definitely work on the issue. But just a small note : This project isn't part of any open source program. But you can surely go ahead, open source doesn't have any boundaries.
